---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
implicit:
  - Сайт должен быть SPA-приложением, которое работает без перезагрузки страницы
  - Данные о заказе должны успешно уходить на сервер
  - После успешного оформления заказа товар должен резервироваться
  - В поля для ввода цены нельзя ввести отрицательное или буквенное значение
  - Поля сайта защищены от XSS атаки
  - Сайт должен хранить информацию о корзине пользователя в сессии браузера
  - Пользователь может выйти из корзины на страницу каталога
  - Пользователь может удалять товары из корзины
  - Сайт должен иметь защищенную страницу оплаты
  - У каталога должно быть несколько страниц
  - Товар должен распределяться равномерно по страница каталога
  - Пользователь должен иметь возможность переключаться с одной страницы каталога на другую
  - При оплате необходимо собрать контактные данные пользователя для обратной связи, например, почту и телефон с помощью формы
  - В карточке товара должны выводиться название, рейтинг, цена со скидкой и без нее и оставшееся количество на складе
  - В каталоге для каждого товара должны выводиться название, рейтинг, цена со скидкой и без нее и оставшееся количество на складе
  - Корзина должна очищаться после успешного оформления заказа
  - Чтобы формировать рейтинг товаров, необходимо собирать отзывы о купленном товаре путем рассылки формы обратной связи после получения заказа или сделать отдельное поле в карточке товара с отзывами покупателей.
